name : SHINOBU

on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ Heroku ]
    
env:
  API_ID: ${{secrets.API_ID}}
  API_HASH: ${{secrets.API_HASH}}
  TOKEN: ${{secrets.TOKEN}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  MONGO_PORT: ${{secrets.MONGO_PORT}}
  MONGO_URI: ${{secrets.MONGO_URI}}
  REM_BG_API_KEY: ${{secrets.REM_BG_API_KEY}}
  TIME_API_KEY: ${{secrets.TIME_API_KEY}}
  WALL_API: ${{secrets.WALL_API}}
  ARQ_API: ${{secrets.ARQ_API}}
  CASH_API_KEY: ${{secrets.CASH_API_KEY}}
  DEMONS: ${{secrets.DEMONS}}
  DEV_USERS: ${{secrets.DEV_USERS}}
  DRAGONS: ${{secrets.DRAGONS}}
  EVENT_LOGS: ${{secrets.EVENT_LOGS}}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - uses: styfle/cancel-workflow-action@0.9.0
       - name: Cancel Previous Runs
         uses: styfle/cancel-workflow-action@0.9.1
         with:
              access_token: ${{ github.token }}
              
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9

       - name: cloning repo and install
         continue-on-error: true
         run: |
           git clone https://${{ secrets.NAME }}:${{ secrets.GIT_TOKEN }}@github.com/ItzKakarotto/Shinobu Shinobu && cd Shinobu && pip3 install -r requirements.txt
           pwd
       - name: Running
         timeout-minutes: 350
         continue-on-error: true
         run: |
           curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -
           pwd
           cd Shinobu
           python3 -m SaitamaRobot
